version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kwongandy/sizepicker
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  trigger-proxy:
    machine: true
    steps:
      - run:
          name: Trigger Proxy
          command: |
            curl -u $PROXY_API_TOKEN: \
            -d 'build_parameters[CIRCLE_JOB]=deploy' \
            https://circleci.com/api/v1.1/project/github/true-barracudas/reviews-proxy/tree/master
  # deploy:
  #   machine:
  #     enabled: true
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - 35:63:29:96:f3:82:08:e1:64:1b:88:54:b9:a2:f8:1a
  #     - run:
  #         name: Deploy over SSH
  #         command: |
  #           ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-160-105-13.us-west-2.compute.amazonaws.com bash -c '\
  #           pwd
  #           cd FEC
  #           pwd
  #           docker-compose pull
  #           docker-compose up -d'
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          context:
            - sizepicker_login
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - publish-latest
      #     filters:
      #       branches:
      #         only: master
      - trigger-proxy:
          context:
            - proxy_context
          requires:
            - publish-latest
          filters:
            branches:
              only: master
