const categories = [
  'Originals',
  'Performance',
  'Running',
  'Hiking',
  'Essentials',
  'Lifestyle',
  'Basketball',
  'Workout',
  'Gym',
  'Clean Classics',
];

const shoeSizes = [
  '5',
  '5.5',
  '6',
  '6.5',
  '7',
  '7.5',
  '8',
  '8.5',
  '9',
  '9.5',
  '10',
  '10.5',
  '11',
  '11.5',
  '12',
  '12.5',
  '13',
  '13.5',
  '14',
];

const shoeName = [
  'NMD_R1 SHOES',
  'ULTRABOOST SHOES',
  'ULTRABOOST ST SHOES',
  'ULTRABOOST DNA SHOES',
  'ULTRABOOST WINTER.RDY SHOES',
  'BUSENITZ PRO SHOES',
  'NIZZA TREFOIL SHOES',
  'ZX 2K BOOST SHOES',
  'OZWEEGO SHOES',
  'NMD_R1 V2 SHOES',
  'ULTRABOOST LTD SHOES',
  'ULTRABOOST 20 SHOES',
  'ADILETTE COMFORT SLIDES',
  'SUN DEVILS ULTRABOOST 1.0 DNA SHOES',
  'ULTRABOOST DNA X REAL MADRID SHOES',
  'KAPTIR SHOES',
  'LITE RACER ADAPT 3.0',
  'SWIFT RUN X SHOES',
  'ZX 2K BOOST SHOES',
  'SUPERSTAR SHOES',
  'ZX 2K 4D SHOES',
  'SUPERNOVA WINTER',
  'RESPONSE SUPER SHOES',
  'CLIMACOOL VENTO SHOES',
  'SUPERCOURT SHOES',
  'DAME 7 SHOES',
  'DONOVAN MITCHELL DON',
  'HARDEN STEPBACK 2',
  'D ROSE 773',
  'D ROSE FAMILY FIRST',
  'PRO MODEL 2G SHOES',
  'HARDEN VOL 4 SHOES',
  'DAME 7 I AM MY OWN FAN',
  'COURT VISION 2.0 SHOES',
  'PRO BOOST LOW SHOES',
  'PRO BOUNCE 2019',
  'PRO MODEL 2G SHOES',
  'DURAMO SL SHOES',
  'GAZELLE VINTAGE SHOES',
  'STAN SMITH SHOES',
  'SAMOA SHOES',
  'RESPONSE SUPER SHOES',
];

const urls = [
  'https://myfecbucket.s3-us-west-1.amazonaws.com/fec+pictures/nmd_rwb/NMD_R1_Shoes_Blue_FV1734_01_standard.jpg',
  'https://myfecbucket.s3-us-west-1.amazonaws.com/fec+pictures/nmd_black/NMD_R1_Shoes_Grey_FV1733_01_standard.jpg',
  'https://myfecbucket.s3-us-west-1.amazonaws.com/fec+pictures/nmd_pur/NMD_R1_Shoes_Black_FV8732_01_standard.jpg',
  'https://myfecbucket.s3-us-west-1.amazonaws.com/fec+pictures/ss_blue/Stan_Smith_Shoes_White_FU9600_01_standard.jpg',
  'https://myfecbucket.s3-us-west-1.amazonaws.com/fec+pictures/ss_green/Stan_Smith_Shoes_White_FU9599_01_standard.jpg',
  'https://myfecbucket.s3-us-west-1.amazonaws.com/fec+pictures/backpack/Utility_Backpack_Orange_EV7559_01_standard.jpg',
];

module.exports = {
  categories,
  shoeSizes,
  shoeName,
  urls,
};
